[package]
name = "yuuskel"
version = "1.0.0"
edition = "2024"
description = "Initialize standardized, reproducible project directories"
license = "MIT"

[dependencies]
dialoguer = "0.12"
chrono = "0.4"
colored = "3.0"
